[versions]
agp = "8.2.1"
kotlin = "1.9.22"
core.ktx = "1.12.0"
lifecycle.runtime.ktx = "2.7.0"
activity.compose = "1.8.2"
compose.bom = "2024.02.00"
lifecycle.viewmodel.compose = "2.7.0"

[libraries]
androidx.core.ktx = { module = "androidx.core:core-ktx", version.ref = "core.ktx" }
androidx.lifecycle.runtime.ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle.runtime.ktx" }
androidx.activity.compose = { module = "androidx.activity:activity-compose", version.ref = "activity.compose" }
androidx.compose.bom = { module = "androidx.compose:compose-bom", version.ref = "compose.bom" }
androidx.ui = { module = "androidx.compose.ui:ui" }
androidx.ui.graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx.ui.tooling.preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx.material3 = { module = "androidx.compose.material3:material3" }
androidx.lifecycle.viewmodel.compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle.viewmodel.compose" }

[plugins]
android.application = { id = "com.android.application", version.ref = "agp" }
kotlin.android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }